### ISSUE TITLE
Can't found get users repos in Postman

### ISSUE THREAD

**Issue by mohamedElheni681** [PacktPublishing/API-Testing-and-Development-with-Postman#18]
In chap 2, I Can't found get users repos in Postman

**Comment by mohamedElheni681** [comment]
> In chap 2, I Can't found get users repos in Postman

Aaa ok , I need to create a fork

**Comment by djwester** [comment]
> > In chap 2, I Can't found get users repos in Postman
> 
> Aaa ok , I need to create a fork

I take it this has been resolved and we can close this issue?
