### ISSUE TITLE
chap 3 : Swagger V3 doesn't work

### ISSUE THREAD

**Issue by mohamedElheni681** [PacktPublishing/API-Testing-and-Development-with-Postman#19]
In chap3: I make two collection one with Swagger V3 and another with V2.
the Swagger v2 work properly but not with the v3 (Status: 404 not Found) .
I thought because there is no pet with id 1, so even with the Post Add a new  pet I received error with status 404.

**Comment by djwester** [comment]
Hi Mohamed, thanks for reaching out about this. There were some changes made on the Postman side after the book was published. If you check out the Errata notes on the main page (https://github.com/PacktPublishing/API-Testing-and-Development-with-Postman) you should see some tweaks to pages 54 and 55 which should make this run more smoothly. 

I hope they help!
